### ISSUE TITLE
Error For Deploy On Heroku

### ISSUE THREAD

**Issue by flaskvol** [anime-republic/MIRROR-HUNTER#16]
2021-10-27T06:25:13.524940+00:00 app[worker.1]: 2021-10-27 06:25:13,524 - root - INFO - Table Created!
2021-10-27T06:25:13.525378+00:00 app[worker.1]: 2021-10-27 06:25:13,525 - bot - INFO - Generating USER_SESSION_STRING
2021-10-27T06:25:13.526318+00:00 app[worker.1]: 2021-10-27 06:25:13,526 - bot - INFO - Generating TELEGRAPH_TOKEN using 'KKVHngHC' name
2021-10-27T06:25:14.919106+00:00 app[worker.1]: Traceback (most recent call last):
2021-10-27T06:25:14.919207+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2021-10-27T06:25:14.919453+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
2021-10-27T06:25:14.919485+00:00 app[worker.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2021-10-27T06:25:14.919706+00:00 app[worker.1]:     exec(code, run_globals)
2021-10-27T06:25:14.919738+00:00 app[worker.1]:   File "/usr/src/app/bot/__main__.py", line 28, in <module>
2021-10-27T06:25:14.919958+00:00 app[worker.1]:     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, delete, usage, count
2021-10-27T06:25:14.919988+00:00 app[worker.1]:   File "/usr/src/app/bot/modules/clone.py", line 21
2021-10-27T06:25:14.920034+00:00 app[worker.1]:     elif reply_to is not None:
2021-10-27T06:25:14.920082+00:00 app[worker.1]:     ^
2021-10-27T06:25:14.920176+00:00 app[worker.1]: SyntaxError: invalid syntax

**Comment by askfriends** [comment]
any update, is it fixed or not?

**Comment by ZekXtreme** [comment]
fixed
