### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by rinrinx** [anime-republic/MIRROR-HUNTER#28]
2022-04-12T23:25:22.310155+00:00 heroku[worker.1]: State changed from starting to up
2022-04-12T23:25:23.149806+00:00 app[worker.1]: warning: no common commits
2022-04-12T23:25:23.374814+00:00 app[worker.1]: 2022-04-12 23:25:23,374 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-04-12T23:25:24.683881+00:00 app[worker.1]: [2022-04-12 23:25:24 +0000] [33] [INFO] Starting gunicorn 20.1.0
2022-04-12T23:25:24.684457+00:00 app[worker.1]: [2022-04-12 23:25:24 +0000] [33] [INFO] Listening at: http://0.0.0.0:23642 (33)
2022-04-12T23:25:24.684527+00:00 app[worker.1]: [2022-04-12 23:25:24 +0000] [33] [INFO] Using worker: sync
2022-04-12T23:25:24.687921+00:00 app[worker.1]: [2022-04-12 23:25:24 +0000] [61] [INFO] Booting worker with pid: 61
2022-04-12T23:25:25.028663+00:00 app[worker.1]: 2022-04-12 23:25:25,028 - root - WARNING - Logs Chat Details not provided!
2022-04-12T23:25:25.028741+00:00 app[worker.1]: 2022-04-12 23:25:25,028 - root - WARNING - LINK_LOGS Chat id not provided, Proceeding Without it
2022-04-12T23:25:25.028802+00:00 app[worker.1]: 2022-04-12 23:25:25,028 - root - WARNING - Leech Log Channel ID not Provided!
2022-04-12T23:25:25.028843+00:00 app[worker.1]: 2022-04-12 23:25:25,028 - root - WARNING - Leech Log alt Channel ID not Provided!
2022-04-12T23:25:25.028891+00:00 app[worker.1]: 2022-04-12 23:25:25,028 - bot - ERROR - One or more env variables missing! Exiting now
2022-04-12T23:25:25.118781+00:00 app[worker.1]: Exception ignored in: <function ClientSession.__del__ at 0x7f19512551f0>
2022-04-12T23:25:25.118782+00:00 app[worker.1]: Traceback (most recent call last):
2022-04-12T23:25:25.118783+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 347, in __del__
2022-04-12T23:25:25.118783+00:00 app[worker.1]:   File "/usr/lib/python3.8/asyncio/base_events.py", line 1740, in call_exception_handler
2022-04-12T23:25:25.118786+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1475, in error
2022-04-12T23:25:25.118787+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
2022-04-12T23:25:25.118787+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
2022-04-12T23:25:25.118787+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
2022-04-12T23:25:25.118787+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
2022-04-12T23:25:25.118788+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1186, in emit
2022-04-12T23:25:25.118788+00:00 app[worker.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
2022-04-12T23:25:25.118788+00:00 app[worker.1]: NameError: name 'open' is not defined
2022-04-12T23:25:25.301227+00:00 heroku[worker.1]: Process exited with status 1
2022-04-12T23:25:25.376714+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by yuno74** [comment]
@rinrinx fill main vars

**Comment by rinrinx** [comment]
BOT_TOKEN = "5172030763:AAGQVn3r2N-RkfqEBl3c6PxlbZUhUxMZH3Y"
GDRIVE_FOLDER_ID = "0AGPq26c9ORHutUk92PVA"
OWNER_ID = 588113120
DOWNLOAD_DIR = "/usr/src/app/downloads"
DOWNLOAD_STATUS_UPDATE_INTERVAL = 5
AUTO_DELETE_MESSAGE_DURATION = -1
AUTO_DELETE_UPLOAD_MESSAGE_DURATION = 120
IS_TEAM_DRIVE = "True"
TELEGRAM_API = 5412487
TELEGRAM_HASH = "37402de39e5eb40d378bf20823db1dfc"


True but not work env problem

**Comment by rinrinx** [comment]
![Screenshot_20220413-095534_Plus](https://user-images.githubusercontent.com/91373907/163117983-ed6c6847-3552-45c5-909d-268f528c2d5a.jpg)

And work but auto down status not work
